apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: m5-ai-inference-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/RoopGuron/llm-operator.git'
    targetRevision: HEAD
    path: gitops-infra/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
