apiVersion: ai.mlo.platform/v1alpha1
kind: LLMOptimizedService
metadata:
  labels:
    app.kubernetes.io/name: llm-icp
    app.kubernetes.io/managed-by: kustomize
  name: llmoptimizedservice-sample
spec:
  # TODO(user): Add fields here
